schemaspy.t=pgsql11
schemaspy.host=host.docker.internal
schemaspy.port=5432
schemaspy.db=outvoice
schemaspy.u=postgres
schemaspy.p=local-db@123
schemaspy.s=public
schemaspy.o=/output
schemaspy.vizjs=true