package com.omkarsathe.outvoice.workspace;

public enum Permission {
    INVOICES_VIEW, INVOICES_CREATE, INVOICES_EDIT, INVOICES_DELETE,
    CUSTOMERS_VIEW, CUSTOMERS_CREATE, CUSTOMERS_EDIT, CUSTOMERS_DELETE,
    AUTOMATION_VIEW, AUTOMATION_CREATE, AUTOMATION_EDIT, AUTOMATION_DELETE,
    LEGAL_SUITE_VIEW, LEGAL_SUITE_CREATE, LEGAL_SUITE_EDIT, LEGAL_SUITE_DELETE,
    SETTINGS_VIEW, SETTINGS_EDIT,
    ROLES_VIEW, ROLES_CREATE, ROLES_EDIT, ROLES_DELETE,
    TEAMS_VIEW, TEAMS_CREATE, TEAMS_EDIT, TEAMS_DELETE,
    INVITES_VIEW, INVITES_CREATE, INVITES_EDIT, INVITES_DELETE,
    WORKSPACE_SETTINGS_VIEW,
    NONE
}
