-- =================================================================
-- V3: Seed data — ISO currencies, countries, phone codes
-- Run after V2 migration. Uses gen_random_uuid() (PostgreSQL 13+).
-- =================================================================

BEGIN;

-- -----------------------------------------------------------------
-- 1. currencies  (155 rows)
-- -----------------------------------------------------------------
INSERT INTO currencies (id, code, name, symbol, decimal_places) VALUES
    (gen_random_uuid(), 'AED', 'UAE Dirham', 'د.إ', 2),
    (gen_random_uuid(), 'AFN', 'Afghan Afghani', '؋', 2),
    (gen_random_uuid(), 'ALL', 'Albanian Lek', 'L', 2),
    (gen_random_uuid(), 'AMD', 'Armenian Dram', '֏', 2),
    (gen_random_uuid(), 'ANG', 'Netherlands Antillean Guilder', 'ƒ', 2),
    (gen_random_uuid(), 'AOA', 'Angolan Kwanza', 'Kz', 2),
    (gen_random_uuid(), 'ARS', 'Argentine Peso', '$', 2),
    (gen_random_uuid(), 'AUD', 'Australian Dollar', '$', 2),
    (gen_random_uuid(), 'AWG', 'Aruban Florin', 'ƒ', 2),
    (gen_random_uuid(), 'AZN', 'Azerbaijani Manat', '₼', 2),
    (gen_random_uuid(), 'BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 2),
    (gen_random_uuid(), 'BBD', 'Barbadian Dollar', '$', 2),
    (gen_random_uuid(), 'BDT', 'Bangladeshi Taka', '৳', 2),
    (gen_random_uuid(), 'BGN', 'Bulgarian Lev', 'лв', 2),
    (gen_random_uuid(), 'BHD', 'Bahraini Dinar', 'BD', 3),
    (gen_random_uuid(), 'BIF', 'Burundian Franc', 'Fr', 0),
    (gen_random_uuid(), 'BMD', 'Bermudian Dollar', '$', 2),
    (gen_random_uuid(), 'BND', 'Brunei Dollar', '$', 2),
    (gen_random_uuid(), 'BOB', 'Bolivian Boliviano', 'Bs.', 2),
    (gen_random_uuid(), 'BRL', 'Brazilian Real', 'R$', 2),
    (gen_random_uuid(), 'BSD', 'Bahamian Dollar', '$', 2),
    (gen_random_uuid(), 'BTN', 'Bhutanese Ngultrum', 'Nu', 2),
    (gen_random_uuid(), 'BWP', 'Botswanan Pula', 'P', 2),
    (gen_random_uuid(), 'BYN', 'Belarusian Ruble', 'Br', 2),
    (gen_random_uuid(), 'BZD', 'Belize Dollar', '$', 2),
    (gen_random_uuid(), 'CAD', 'Canadian Dollar', '$', 2),
    (gen_random_uuid(), 'CDF', 'Congolese Franc', 'Fr', 2),
    (gen_random_uuid(), 'CHF', 'Swiss Franc', 'Fr', 2),
    (gen_random_uuid(), 'CLP', 'Chilean Peso', '$', 0),
    (gen_random_uuid(), 'CNY', 'Chinese Yuan', '¥', 2),
    (gen_random_uuid(), 'COP', 'Colombian Peso', '$', 2),
    (gen_random_uuid(), 'CRC', 'Costa Rican Colon', '₡', 2),
    (gen_random_uuid(), 'CUP', 'Cuban Peso', '$', 2),
    (gen_random_uuid(), 'CVE', 'Cape Verdean Escudo', '$', 2),
    (gen_random_uuid(), 'CZK', 'Czech Koruna', 'Kc', 2),
    (gen_random_uuid(), 'DJF', 'Djiboutian Franc', 'Fr', 0),
    (gen_random_uuid(), 'DKK', 'Danish Krone', 'kr', 2),
    (gen_random_uuid(), 'DOP', 'Dominican Peso', '$', 2),
    (gen_random_uuid(), 'DZD', 'Algerian Dinar', 'DA', 2),
    (gen_random_uuid(), 'EGP', 'Egyptian Pound', 'E£', 2),
    (gen_random_uuid(), 'ERN', 'Eritrean Nakfa', 'Nfk', 2),
    (gen_random_uuid(), 'ETB', 'Ethiopian Birr', 'Br', 2),
    (gen_random_uuid(), 'EUR', 'Euro', '€', 2),
    (gen_random_uuid(), 'FJD', 'Fijian Dollar', '$', 2),
    (gen_random_uuid(), 'FKP', 'Falkland Islands Pound', '£', 2),
    (gen_random_uuid(), 'GBP', 'British Pound Sterling', '£', 2),
    (gen_random_uuid(), 'GEL', 'Georgian Lari', '₾', 2),
    (gen_random_uuid(), 'GHS', 'Ghanaian Cedi', '₵', 2),
    (gen_random_uuid(), 'GIP', 'Gibraltar Pound', '£', 2),
    (gen_random_uuid(), 'GMD', 'Gambian Dalasi', 'D', 2),
    (gen_random_uuid(), 'GNF', 'Guinean Franc', 'Fr', 0),
    (gen_random_uuid(), 'GTQ', 'Guatemalan Quetzal', 'Q', 2),
    (gen_random_uuid(), 'GYD', 'Guyanese Dollar', '$', 2),
    (gen_random_uuid(), 'HKD', 'Hong Kong Dollar', '$', 2),
    (gen_random_uuid(), 'HNL', 'Honduran Lempira', 'L', 2),
    (gen_random_uuid(), 'HRK', 'Croatian Kuna', 'kn', 2),
    (gen_random_uuid(), 'HTG', 'Haitian Gourde', 'G', 2),
    (gen_random_uuid(), 'HUF', 'Hungarian Forint', 'Ft', 2),
    (gen_random_uuid(), 'IDR', 'Indonesian Rupiah', 'Rp', 2),
    (gen_random_uuid(), 'ILS', 'Israeli New Shekel', '₪', 2),
    (gen_random_uuid(), 'INR', 'Indian Rupee', '₹', 2),
    (gen_random_uuid(), 'IQD', 'Iraqi Dinar', 'IQD', 3),
    (gen_random_uuid(), 'IRR', 'Iranian Rial', 'IRR', 2),
    (gen_random_uuid(), 'ISK', 'Icelandic Krona', 'kr', 0),
    (gen_random_uuid(), 'JMD', 'Jamaican Dollar', '$', 2),
    (gen_random_uuid(), 'JOD', 'Jordanian Dinar', 'JD', 3),
    (gen_random_uuid(), 'JPY', 'Japanese Yen', '¥', 0),
    (gen_random_uuid(), 'KES', 'Kenyan Shilling', 'KSh', 2),
    (gen_random_uuid(), 'KGS', 'Kyrgystani Som', 'c', 2),
    (gen_random_uuid(), 'KHR', 'Cambodian Riel', 'KHR', 2),
    (gen_random_uuid(), 'KMF', 'Comorian Franc', 'Fr', 0),
    (gen_random_uuid(), 'KPW', 'North Korean Won', 'KPW', 2),
    (gen_random_uuid(), 'KRW', 'South Korean Won', '₩', 0),
    (gen_random_uuid(), 'KWD', 'Kuwaiti Dinar', 'KD', 3),
    (gen_random_uuid(), 'KYD', 'Cayman Islands Dollar', '$', 2),
    (gen_random_uuid(), 'KZT', 'Kazakhstani Tenge', '₸', 2),
    (gen_random_uuid(), 'LAK', 'Laotian Kip', 'LAK', 2),
    (gen_random_uuid(), 'LBP', 'Lebanese Pound', 'LL', 2),
    (gen_random_uuid(), 'LKR', 'Sri Lankan Rupee', 'Rs', 2),
    (gen_random_uuid(), 'LRD', 'Liberian Dollar', '$', 2),
    (gen_random_uuid(), 'LSL', 'Lesotho Loti', 'L', 2),
    (gen_random_uuid(), 'LYD', 'Libyan Dinar', 'LD', 3),
    (gen_random_uuid(), 'MAD', 'Moroccan Dirham', 'MAD', 2),
    (gen_random_uuid(), 'MDL', 'Moldovan Leu', 'L', 2),
    (gen_random_uuid(), 'MGA', 'Malagasy Ariary', 'Ar', 2),
    (gen_random_uuid(), 'MKD', 'Macedonian Denar', 'MKD', 2),
    (gen_random_uuid(), 'MMK', 'Myanmar Kyat', 'K', 2),
    (gen_random_uuid(), 'MNT', 'Mongolian Tugrik', '₮', 2),
    (gen_random_uuid(), 'MOP', 'Macanese Pataca', 'P', 2),
    (gen_random_uuid(), 'MRU', 'Mauritanian Ouguiya', 'UM', 2),
    (gen_random_uuid(), 'MUR', 'Mauritian Rupee', 'Rs', 2),
    (gen_random_uuid(), 'MVR', 'Maldivian Rufiyaa', 'MVR', 2),
    (gen_random_uuid(), 'MWK', 'Malawian Kwacha', 'MK', 2),
    (gen_random_uuid(), 'MXN', 'Mexican Peso', '$', 2),
    (gen_random_uuid(), 'MYR', 'Malaysian Ringgit', 'RM', 2),
    (gen_random_uuid(), 'MZN', 'Mozambican Metical', 'MT', 2),
    (gen_random_uuid(), 'NAD', 'Namibian Dollar', '$', 2),
    (gen_random_uuid(), 'NGN', 'Nigerian Naira', '₦', 2),
    (gen_random_uuid(), 'NIO', 'Nicaraguan Cordoba', 'C$', 2),
    (gen_random_uuid(), 'NOK', 'Norwegian Krone', 'kr', 2),
    (gen_random_uuid(), 'NPR', 'Nepalese Rupee', 'Rs', 2),
    (gen_random_uuid(), 'NZD', 'New Zealand Dollar', '$', 2),
    (gen_random_uuid(), 'OMR', 'Omani Rial', 'OMR', 3),
    (gen_random_uuid(), 'PAB', 'Panamanian Balboa', 'B/.', 2),
    (gen_random_uuid(), 'PEN', 'Peruvian Sol', 'S/.', 2),
    (gen_random_uuid(), 'PGK', 'Papua New Guinean Kina', 'K', 2),
    (gen_random_uuid(), 'PHP', 'Philippine Peso', '₱', 2),
    (gen_random_uuid(), 'PKR', 'Pakistani Rupee', 'Rs', 2),
    (gen_random_uuid(), 'PLN', 'Polish Zloty', 'zl', 2),
    (gen_random_uuid(), 'PYG', 'Paraguayan Guarani', 'PYG', 0),
    (gen_random_uuid(), 'QAR', 'Qatari Riyal', 'QAR', 2),
    (gen_random_uuid(), 'RON', 'Romanian Leu', 'lei', 2),
    (gen_random_uuid(), 'RSD', 'Serbian Dinar', 'din', 2),
    (gen_random_uuid(), 'RUB', 'Russian Ruble', '₽', 2),
    (gen_random_uuid(), 'RWF', 'Rwandan Franc', 'Fr', 0),
    (gen_random_uuid(), 'SAR', 'Saudi Riyal', 'SAR', 2),
    (gen_random_uuid(), 'SBD', 'Solomon Islands Dollar', '$', 2),
    (gen_random_uuid(), 'SCR', 'Seychellois Rupee', 'Rs', 2),
    (gen_random_uuid(), 'SDG', 'Sudanese Pound', 'SDG', 2),
    (gen_random_uuid(), 'SEK', 'Swedish Krona', 'kr', 2),
    (gen_random_uuid(), 'SGD', 'Singapore Dollar', '$', 2),
    (gen_random_uuid(), 'SHP', 'Saint Helena Pound', '£', 2),
    (gen_random_uuid(), 'SLL', 'Sierra Leonean Leone', 'Le', 2),
    (gen_random_uuid(), 'SOS', 'Somali Shilling', 'Sh', 2),
    (gen_random_uuid(), 'SRD', 'Surinamese Dollar', '$', 2),
    (gen_random_uuid(), 'STN', 'Sao Tome and Principe Dobra', 'Db', 2),
    (gen_random_uuid(), 'SVC', 'Salvadoran Colon', 'SVC', 2),
    (gen_random_uuid(), 'SYP', 'Syrian Pound', 'SYP', 2),
    (gen_random_uuid(), 'SZL', 'Swazi Lilangeni', 'L', 2),
    (gen_random_uuid(), 'THB', 'Thai Baht', '฿', 2),
    (gen_random_uuid(), 'TJS', 'Tajikistani Somoni', 'SM', 2),
    (gen_random_uuid(), 'TMT', 'Turkmenistani Manat', 'T', 2),
    (gen_random_uuid(), 'TND', 'Tunisian Dinar', 'DT', 3),
    (gen_random_uuid(), 'TOP', 'Tongan Paanga', 'T$', 2),
    (gen_random_uuid(), 'TRY', 'Turkish Lira', '₺', 2),
    (gen_random_uuid(), 'TTD', 'Trinidad and Tobago Dollar', '$', 2),
    (gen_random_uuid(), 'TWD', 'New Taiwan Dollar', '$', 2),
    (gen_random_uuid(), 'TZS', 'Tanzanian Shilling', 'Sh', 2),
    (gen_random_uuid(), 'UAH', 'Ukrainian Hryvnia', '₴', 2),
    (gen_random_uuid(), 'UGX', 'Ugandan Shilling', 'Sh', 0),
    (gen_random_uuid(), 'USD', 'United States Dollar', '$', 2),
    (gen_random_uuid(), 'UYU', 'Uruguayan Peso', '$', 2),
    (gen_random_uuid(), 'UZS', 'Uzbekistani Som', 'UZS', 2),
    (gen_random_uuid(), 'VES', 'Venezuelan Bolivar Soberano', 'Bs.S', 2),
    (gen_random_uuid(), 'VND', 'Vietnamese Dong', '₫', 0),
    (gen_random_uuid(), 'VUV', 'Vanuatu Vatu', 'Vt', 0),
    (gen_random_uuid(), 'WST', 'Samoan Tala', 'T', 2),
    (gen_random_uuid(), 'XAF', 'Central African CFA Franc', 'Fr', 0),
    (gen_random_uuid(), 'XCD', 'East Caribbean Dollar', '$', 2),
    (gen_random_uuid(), 'XOF', 'West African CFA Franc', 'Fr', 0),
    (gen_random_uuid(), 'XPF', 'CFP Franc', 'Fr', 0),
    (gen_random_uuid(), 'YER', 'Yemeni Rial', 'YER', 2),
    (gen_random_uuid(), 'ZAR', 'South African Rand', 'R', 2),
    (gen_random_uuid(), 'ZMW', 'Zambian Kwacha', 'ZK', 2),
    (gen_random_uuid(), 'ZWL', 'Zimbabwean Dollar', '$', 2);

-- -----------------------------------------------------------------
-- 2. phone_codes  (183 rows)
-- -----------------------------------------------------------------
INSERT INTO phone_codes (id, code) VALUES
    (gen_random_uuid(), '+1'),
    (gen_random_uuid(), '+7'),
    (gen_random_uuid(), '+20'),
    (gen_random_uuid(), '+27'),
    (gen_random_uuid(), '+30'),
    (gen_random_uuid(), '+31'),
    (gen_random_uuid(), '+32'),
    (gen_random_uuid(), '+33'),
    (gen_random_uuid(), '+34'),
    (gen_random_uuid(), '+36'),
    (gen_random_uuid(), '+39'),
    (gen_random_uuid(), '+40'),
    (gen_random_uuid(), '+41'),
    (gen_random_uuid(), '+43'),
    (gen_random_uuid(), '+44'),
    (gen_random_uuid(), '+45'),
    (gen_random_uuid(), '+46'),
    (gen_random_uuid(), '+47'),
    (gen_random_uuid(), '+48'),
    (gen_random_uuid(), '+49'),
    (gen_random_uuid(), '+51'),
    (gen_random_uuid(), '+52'),
    (gen_random_uuid(), '+53'),
    (gen_random_uuid(), '+54'),
    (gen_random_uuid(), '+55'),
    (gen_random_uuid(), '+56'),
    (gen_random_uuid(), '+57'),
    (gen_random_uuid(), '+58'),
    (gen_random_uuid(), '+60'),
    (gen_random_uuid(), '+61'),
    (gen_random_uuid(), '+62'),
    (gen_random_uuid(), '+63'),
    (gen_random_uuid(), '+64'),
    (gen_random_uuid(), '+65'),
    (gen_random_uuid(), '+66'),
    (gen_random_uuid(), '+81'),
    (gen_random_uuid(), '+82'),
    (gen_random_uuid(), '+84'),
    (gen_random_uuid(), '+86'),
    (gen_random_uuid(), '+90'),
    (gen_random_uuid(), '+91'),
    (gen_random_uuid(), '+92'),
    (gen_random_uuid(), '+93'),
    (gen_random_uuid(), '+94'),
    (gen_random_uuid(), '+95'),
    (gen_random_uuid(), '+98'),
    (gen_random_uuid(), '+212'),
    (gen_random_uuid(), '+213'),
    (gen_random_uuid(), '+216'),
    (gen_random_uuid(), '+218'),
    (gen_random_uuid(), '+220'),
    (gen_random_uuid(), '+221'),
    (gen_random_uuid(), '+222'),
    (gen_random_uuid(), '+223'),
    (gen_random_uuid(), '+224'),
    (gen_random_uuid(), '+226'),
    (gen_random_uuid(), '+227'),
    (gen_random_uuid(), '+228'),
    (gen_random_uuid(), '+229'),
    (gen_random_uuid(), '+230'),
    (gen_random_uuid(), '+231'),
    (gen_random_uuid(), '+232'),
    (gen_random_uuid(), '+233'),
    (gen_random_uuid(), '+234'),
    (gen_random_uuid(), '+235'),
    (gen_random_uuid(), '+236'),
    (gen_random_uuid(), '+237'),
    (gen_random_uuid(), '+238'),
    (gen_random_uuid(), '+239'),
    (gen_random_uuid(), '+240'),
    (gen_random_uuid(), '+241'),
    (gen_random_uuid(), '+242'),
    (gen_random_uuid(), '+243'),
    (gen_random_uuid(), '+244'),
    (gen_random_uuid(), '+245'),
    (gen_random_uuid(), '+248'),
    (gen_random_uuid(), '+249'),
    (gen_random_uuid(), '+250'),
    (gen_random_uuid(), '+251'),
    (gen_random_uuid(), '+252'),
    (gen_random_uuid(), '+253'),
    (gen_random_uuid(), '+254'),
    (gen_random_uuid(), '+255'),
    (gen_random_uuid(), '+256'),
    (gen_random_uuid(), '+257'),
    (gen_random_uuid(), '+258'),
    (gen_random_uuid(), '+260'),
    (gen_random_uuid(), '+261'),
    (gen_random_uuid(), '+263'),
    (gen_random_uuid(), '+264'),
    (gen_random_uuid(), '+265'),
    (gen_random_uuid(), '+266'),
    (gen_random_uuid(), '+267'),
    (gen_random_uuid(), '+268'),
    (gen_random_uuid(), '+269'),
    (gen_random_uuid(), '+291'),
    (gen_random_uuid(), '+350'),
    (gen_random_uuid(), '+351'),
    (gen_random_uuid(), '+352'),
    (gen_random_uuid(), '+353'),
    (gen_random_uuid(), '+354'),
    (gen_random_uuid(), '+355'),
    (gen_random_uuid(), '+356'),
    (gen_random_uuid(), '+357'),
    (gen_random_uuid(), '+358'),
    (gen_random_uuid(), '+359'),
    (gen_random_uuid(), '+370'),
    (gen_random_uuid(), '+371'),
    (gen_random_uuid(), '+372'),
    (gen_random_uuid(), '+373'),
    (gen_random_uuid(), '+374'),
    (gen_random_uuid(), '+375'),
    (gen_random_uuid(), '+376'),
    (gen_random_uuid(), '+377'),
    (gen_random_uuid(), '+380'),
    (gen_random_uuid(), '+381'),
    (gen_random_uuid(), '+382'),
    (gen_random_uuid(), '+385'),
    (gen_random_uuid(), '+386'),
    (gen_random_uuid(), '+387'),
    (gen_random_uuid(), '+389'),
    (gen_random_uuid(), '+420'),
    (gen_random_uuid(), '+421'),
    (gen_random_uuid(), '+423'),
    (gen_random_uuid(), '+500'),
    (gen_random_uuid(), '+501'),
    (gen_random_uuid(), '+502'),
    (gen_random_uuid(), '+503'),
    (gen_random_uuid(), '+504'),
    (gen_random_uuid(), '+505'),
    (gen_random_uuid(), '+506'),
    (gen_random_uuid(), '+507'),
    (gen_random_uuid(), '+509'),
    (gen_random_uuid(), '+591'),
    (gen_random_uuid(), '+592'),
    (gen_random_uuid(), '+593'),
    (gen_random_uuid(), '+595'),
    (gen_random_uuid(), '+597'),
    (gen_random_uuid(), '+598'),
    (gen_random_uuid(), '+670'),
    (gen_random_uuid(), '+673'),
    (gen_random_uuid(), '+674'),
    (gen_random_uuid(), '+675'),
    (gen_random_uuid(), '+676'),
    (gen_random_uuid(), '+677'),
    (gen_random_uuid(), '+678'),
    (gen_random_uuid(), '+679'),
    (gen_random_uuid(), '+680'),
    (gen_random_uuid(), '+685'),
    (gen_random_uuid(), '+686'),
    (gen_random_uuid(), '+688'),
    (gen_random_uuid(), '+691'),
    (gen_random_uuid(), '+692'),
    (gen_random_uuid(), '+850'),
    (gen_random_uuid(), '+852'),
    (gen_random_uuid(), '+853'),
    (gen_random_uuid(), '+855'),
    (gen_random_uuid(), '+856'),
    (gen_random_uuid(), '+880'),
    (gen_random_uuid(), '+886'),
    (gen_random_uuid(), '+960'),
    (gen_random_uuid(), '+961'),
    (gen_random_uuid(), '+962'),
    (gen_random_uuid(), '+963'),
    (gen_random_uuid(), '+964'),
    (gen_random_uuid(), '+965'),
    (gen_random_uuid(), '+966'),
    (gen_random_uuid(), '+967'),
    (gen_random_uuid(), '+968'),
    (gen_random_uuid(), '+970'),
    (gen_random_uuid(), '+971'),
    (gen_random_uuid(), '+972'),
    (gen_random_uuid(), '+973'),
    (gen_random_uuid(), '+974'),
    (gen_random_uuid(), '+975'),
    (gen_random_uuid(), '+976'),
    (gen_random_uuid(), '+977'),
    (gen_random_uuid(), '+992'),
    (gen_random_uuid(), '+993'),
    (gen_random_uuid(), '+994'),
    (gen_random_uuid(), '+995'),
    (gen_random_uuid(), '+996'),
    (gen_random_uuid(), '+998');

-- -----------------------------------------------------------------
-- 3. countries  (195 rows)
-- -----------------------------------------------------------------
INSERT INTO countries (id, name, iso_code_2, iso_code_3, default_currency_id) VALUES
    (gen_random_uuid(), 'Afghanistan', 'AF', 'AFG',
        (SELECT id FROM currencies WHERE code = 'AFN')),
    (gen_random_uuid(), 'Albania', 'AL', 'ALB',
        (SELECT id FROM currencies WHERE code = 'ALL')),
    (gen_random_uuid(), 'Algeria', 'DZ', 'DZA',
        (SELECT id FROM currencies WHERE code = 'DZD')),
    (gen_random_uuid(), 'Andorra', 'AD', 'AND',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Angola', 'AO', 'AGO',
        (SELECT id FROM currencies WHERE code = 'AOA')),
    (gen_random_uuid(), 'Antigua and Barbuda', 'AG', 'ATG',
        (SELECT id FROM currencies WHERE code = 'XCD')),
    (gen_random_uuid(), 'Argentina', 'AR', 'ARG',
        (SELECT id FROM currencies WHERE code = 'ARS')),
    (gen_random_uuid(), 'Armenia', 'AM', 'ARM',
        (SELECT id FROM currencies WHERE code = 'AMD')),
    (gen_random_uuid(), 'Australia', 'AU', 'AUS',
        (SELECT id FROM currencies WHERE code = 'AUD')),
    (gen_random_uuid(), 'Austria', 'AT', 'AUT',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Azerbaijan', 'AZ', 'AZE',
        (SELECT id FROM currencies WHERE code = 'AZN')),
    (gen_random_uuid(), 'Bahamas', 'BS', 'BHS',
        (SELECT id FROM currencies WHERE code = 'BSD')),
    (gen_random_uuid(), 'Bahrain', 'BH', 'BHR',
        (SELECT id FROM currencies WHERE code = 'BHD')),
    (gen_random_uuid(), 'Bangladesh', 'BD', 'BGD',
        (SELECT id FROM currencies WHERE code = 'BDT')),
    (gen_random_uuid(), 'Barbados', 'BB', 'BRB',
        (SELECT id FROM currencies WHERE code = 'BBD')),
    (gen_random_uuid(), 'Belarus', 'BY', 'BLR',
        (SELECT id FROM currencies WHERE code = 'BYN')),
    (gen_random_uuid(), 'Belgium', 'BE', 'BEL',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Belize', 'BZ', 'BLZ',
        (SELECT id FROM currencies WHERE code = 'BZD')),
    (gen_random_uuid(), 'Benin', 'BJ', 'BEN',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Bhutan', 'BT', 'BTN',
        (SELECT id FROM currencies WHERE code = 'BTN')),
    (gen_random_uuid(), 'Bolivia', 'BO', 'BOL',
        (SELECT id FROM currencies WHERE code = 'BOB')),
    (gen_random_uuid(), 'Bosnia and Herzegovina', 'BA', 'BIH',
        (SELECT id FROM currencies WHERE code = 'BAM')),
    (gen_random_uuid(), 'Botswana', 'BW', 'BWA',
        (SELECT id FROM currencies WHERE code = 'BWP')),
    (gen_random_uuid(), 'Brazil', 'BR', 'BRA',
        (SELECT id FROM currencies WHERE code = 'BRL')),
    (gen_random_uuid(), 'Brunei', 'BN', 'BRN',
        (SELECT id FROM currencies WHERE code = 'BND')),
    (gen_random_uuid(), 'Bulgaria', 'BG', 'BGR',
        (SELECT id FROM currencies WHERE code = 'BGN')),
    (gen_random_uuid(), 'Burkina Faso', 'BF', 'BFA',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Burundi', 'BI', 'BDI',
        (SELECT id FROM currencies WHERE code = 'BIF')),
    (gen_random_uuid(), 'Cabo Verde', 'CV', 'CPV',
        (SELECT id FROM currencies WHERE code = 'CVE')),
    (gen_random_uuid(), 'Cambodia', 'KH', 'KHM',
        (SELECT id FROM currencies WHERE code = 'KHR')),
    (gen_random_uuid(), 'Cameroon', 'CM', 'CMR',
        (SELECT id FROM currencies WHERE code = 'XAF')),
    (gen_random_uuid(), 'Canada', 'CA', 'CAN',
        (SELECT id FROM currencies WHERE code = 'CAD')),
    (gen_random_uuid(), 'Central African Republic', 'CF', 'CAF',
        (SELECT id FROM currencies WHERE code = 'XAF')),
    (gen_random_uuid(), 'Chad', 'TD', 'TCD',
        (SELECT id FROM currencies WHERE code = 'XAF')),
    (gen_random_uuid(), 'Chile', 'CL', 'CHL',
        (SELECT id FROM currencies WHERE code = 'CLP')),
    (gen_random_uuid(), 'China', 'CN', 'CHN',
        (SELECT id FROM currencies WHERE code = 'CNY')),
    (gen_random_uuid(), 'Colombia', 'CO', 'COL',
        (SELECT id FROM currencies WHERE code = 'COP')),
    (gen_random_uuid(), 'Comoros', 'KM', 'COM',
        (SELECT id FROM currencies WHERE code = 'KMF')),
    (gen_random_uuid(), 'Congo Republic', 'CG', 'COG',
        (SELECT id FROM currencies WHERE code = 'XAF')),
    (gen_random_uuid(), 'Congo DR', 'CD', 'COD',
        (SELECT id FROM currencies WHERE code = 'CDF')),
    (gen_random_uuid(), 'Costa Rica', 'CR', 'CRI',
        (SELECT id FROM currencies WHERE code = 'CRC')),
    (gen_random_uuid(), 'Croatia', 'HR', 'HRV',
        (SELECT id FROM currencies WHERE code = 'HRK')),
    (gen_random_uuid(), 'Cuba', 'CU', 'CUB',
        (SELECT id FROM currencies WHERE code = 'CUP')),
    (gen_random_uuid(), 'Cyprus', 'CY', 'CYP',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Czech Republic', 'CZ', 'CZE',
        (SELECT id FROM currencies WHERE code = 'CZK')),
    (gen_random_uuid(), 'Denmark', 'DK', 'DNK',
        (SELECT id FROM currencies WHERE code = 'DKK')),
    (gen_random_uuid(), 'Djibouti', 'DJ', 'DJI',
        (SELECT id FROM currencies WHERE code = 'DJF')),
    (gen_random_uuid(), 'Dominica', 'DM', 'DMA',
        (SELECT id FROM currencies WHERE code = 'XCD')),
    (gen_random_uuid(), 'Dominican Republic', 'DO', 'DOM',
        (SELECT id FROM currencies WHERE code = 'DOP')),
    (gen_random_uuid(), 'Ecuador', 'EC', 'ECU',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Egypt', 'EG', 'EGY',
        (SELECT id FROM currencies WHERE code = 'EGP')),
    (gen_random_uuid(), 'El Salvador', 'SV', 'SLV',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Equatorial Guinea', 'GQ', 'GNQ',
        (SELECT id FROM currencies WHERE code = 'XAF')),
    (gen_random_uuid(), 'Eritrea', 'ER', 'ERI',
        (SELECT id FROM currencies WHERE code = 'ERN')),
    (gen_random_uuid(), 'Estonia', 'EE', 'EST',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Eswatini', 'SZ', 'SWZ',
        (SELECT id FROM currencies WHERE code = 'SZL')),
    (gen_random_uuid(), 'Ethiopia', 'ET', 'ETH',
        (SELECT id FROM currencies WHERE code = 'ETB')),
    (gen_random_uuid(), 'Fiji', 'FJ', 'FJI',
        (SELECT id FROM currencies WHERE code = 'FJD')),
    (gen_random_uuid(), 'Finland', 'FI', 'FIN',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'France', 'FR', 'FRA',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Gabon', 'GA', 'GAB',
        (SELECT id FROM currencies WHERE code = 'XAF')),
    (gen_random_uuid(), 'Gambia', 'GM', 'GMB',
        (SELECT id FROM currencies WHERE code = 'GMD')),
    (gen_random_uuid(), 'Georgia', 'GE', 'GEO',
        (SELECT id FROM currencies WHERE code = 'GEL')),
    (gen_random_uuid(), 'Germany', 'DE', 'DEU',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Ghana', 'GH', 'GHA',
        (SELECT id FROM currencies WHERE code = 'GHS')),
    (gen_random_uuid(), 'Greece', 'GR', 'GRC',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Grenada', 'GD', 'GRD',
        (SELECT id FROM currencies WHERE code = 'XCD')),
    (gen_random_uuid(), 'Guatemala', 'GT', 'GTM',
        (SELECT id FROM currencies WHERE code = 'GTQ')),
    (gen_random_uuid(), 'Guinea', 'GN', 'GIN',
        (SELECT id FROM currencies WHERE code = 'GNF')),
    (gen_random_uuid(), 'Guinea-Bissau', 'GW', 'GNB',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Guyana', 'GY', 'GUY',
        (SELECT id FROM currencies WHERE code = 'GYD')),
    (gen_random_uuid(), 'Haiti', 'HT', 'HTI',
        (SELECT id FROM currencies WHERE code = 'HTG')),
    (gen_random_uuid(), 'Honduras', 'HN', 'HND',
        (SELECT id FROM currencies WHERE code = 'HNL')),
    (gen_random_uuid(), 'Hungary', 'HU', 'HUN',
        (SELECT id FROM currencies WHERE code = 'HUF')),
    (gen_random_uuid(), 'Iceland', 'IS', 'ISL',
        (SELECT id FROM currencies WHERE code = 'ISK')),
    (gen_random_uuid(), 'India', 'IN', 'IND',
        (SELECT id FROM currencies WHERE code = 'INR')),
    (gen_random_uuid(), 'Indonesia', 'ID', 'IDN',
        (SELECT id FROM currencies WHERE code = 'IDR')),
    (gen_random_uuid(), 'Iran', 'IR', 'IRN',
        (SELECT id FROM currencies WHERE code = 'IRR')),
    (gen_random_uuid(), 'Iraq', 'IQ', 'IRQ',
        (SELECT id FROM currencies WHERE code = 'IQD')),
    (gen_random_uuid(), 'Ireland', 'IE', 'IRL',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Israel', 'IL', 'ISR',
        (SELECT id FROM currencies WHERE code = 'ILS')),
    (gen_random_uuid(), 'Italy', 'IT', 'ITA',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Jamaica', 'JM', 'JAM',
        (SELECT id FROM currencies WHERE code = 'JMD')),
    (gen_random_uuid(), 'Japan', 'JP', 'JPN',
        (SELECT id FROM currencies WHERE code = 'JPY')),
    (gen_random_uuid(), 'Jordan', 'JO', 'JOR',
        (SELECT id FROM currencies WHERE code = 'JOD')),
    (gen_random_uuid(), 'Kazakhstan', 'KZ', 'KAZ',
        (SELECT id FROM currencies WHERE code = 'KZT')),
    (gen_random_uuid(), 'Kenya', 'KE', 'KEN',
        (SELECT id FROM currencies WHERE code = 'KES')),
    (gen_random_uuid(), 'Kiribati', 'KI', 'KIR',
        (SELECT id FROM currencies WHERE code = 'AUD')),
    (gen_random_uuid(), 'Kuwait', 'KW', 'KWT',
        (SELECT id FROM currencies WHERE code = 'KWD')),
    (gen_random_uuid(), 'Kyrgyzstan', 'KG', 'KGZ',
        (SELECT id FROM currencies WHERE code = 'KGS')),
    (gen_random_uuid(), 'Laos', 'LA', 'LAO',
        (SELECT id FROM currencies WHERE code = 'LAK')),
    (gen_random_uuid(), 'Latvia', 'LV', 'LVA',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Lebanon', 'LB', 'LBN',
        (SELECT id FROM currencies WHERE code = 'LBP')),
    (gen_random_uuid(), 'Lesotho', 'LS', 'LSO',
        (SELECT id FROM currencies WHERE code = 'LSL')),
    (gen_random_uuid(), 'Liberia', 'LR', 'LBR',
        (SELECT id FROM currencies WHERE code = 'LRD')),
    (gen_random_uuid(), 'Libya', 'LY', 'LBY',
        (SELECT id FROM currencies WHERE code = 'LYD')),
    (gen_random_uuid(), 'Liechtenstein', 'LI', 'LIE',
        (SELECT id FROM currencies WHERE code = 'CHF')),
    (gen_random_uuid(), 'Lithuania', 'LT', 'LTU',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Luxembourg', 'LU', 'LUX',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Madagascar', 'MG', 'MDG',
        (SELECT id FROM currencies WHERE code = 'MGA')),
    (gen_random_uuid(), 'Malawi', 'MW', 'MWI',
        (SELECT id FROM currencies WHERE code = 'MWK')),
    (gen_random_uuid(), 'Malaysia', 'MY', 'MYS',
        (SELECT id FROM currencies WHERE code = 'MYR')),
    (gen_random_uuid(), 'Maldives', 'MV', 'MDV',
        (SELECT id FROM currencies WHERE code = 'MVR')),
    (gen_random_uuid(), 'Mali', 'ML', 'MLI',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Malta', 'MT', 'MLT',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Marshall Islands', 'MH', 'MHL',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Mauritania', 'MR', 'MRT',
        (SELECT id FROM currencies WHERE code = 'MRU')),
    (gen_random_uuid(), 'Mauritius', 'MU', 'MUS',
        (SELECT id FROM currencies WHERE code = 'MUR')),
    (gen_random_uuid(), 'Mexico', 'MX', 'MEX',
        (SELECT id FROM currencies WHERE code = 'MXN')),
    (gen_random_uuid(), 'Micronesia', 'FM', 'FSM',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Moldova', 'MD', 'MDA',
        (SELECT id FROM currencies WHERE code = 'MDL')),
    (gen_random_uuid(), 'Monaco', 'MC', 'MCO',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Mongolia', 'MN', 'MNG',
        (SELECT id FROM currencies WHERE code = 'MNT')),
    (gen_random_uuid(), 'Montenegro', 'ME', 'MNE',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Morocco', 'MA', 'MAR',
        (SELECT id FROM currencies WHERE code = 'MAD')),
    (gen_random_uuid(), 'Mozambique', 'MZ', 'MOZ',
        (SELECT id FROM currencies WHERE code = 'MZN')),
    (gen_random_uuid(), 'Myanmar', 'MM', 'MMR',
        (SELECT id FROM currencies WHERE code = 'MMK')),
    (gen_random_uuid(), 'Namibia', 'NA', 'NAM',
        (SELECT id FROM currencies WHERE code = 'NAD')),
    (gen_random_uuid(), 'Nauru', 'NR', 'NRU',
        (SELECT id FROM currencies WHERE code = 'AUD')),
    (gen_random_uuid(), 'Nepal', 'NP', 'NPL',
        (SELECT id FROM currencies WHERE code = 'NPR')),
    (gen_random_uuid(), 'Netherlands', 'NL', 'NLD',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'New Zealand', 'NZ', 'NZL',
        (SELECT id FROM currencies WHERE code = 'NZD')),
    (gen_random_uuid(), 'Nicaragua', 'NI', 'NIC',
        (SELECT id FROM currencies WHERE code = 'NIO')),
    (gen_random_uuid(), 'Niger', 'NE', 'NER',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Nigeria', 'NG', 'NGA',
        (SELECT id FROM currencies WHERE code = 'NGN')),
    (gen_random_uuid(), 'North Korea', 'KP', 'PRK',
        (SELECT id FROM currencies WHERE code = 'KPW')),
    (gen_random_uuid(), 'North Macedonia', 'MK', 'MKD',
        (SELECT id FROM currencies WHERE code = 'MKD')),
    (gen_random_uuid(), 'Norway', 'NO', 'NOR',
        (SELECT id FROM currencies WHERE code = 'NOK')),
    (gen_random_uuid(), 'Oman', 'OM', 'OMN',
        (SELECT id FROM currencies WHERE code = 'OMR')),
    (gen_random_uuid(), 'Pakistan', 'PK', 'PAK',
        (SELECT id FROM currencies WHERE code = 'PKR')),
    (gen_random_uuid(), 'Palau', 'PW', 'PLW',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Palestine', 'PS', 'PSE',
        (SELECT id FROM currencies WHERE code = 'ILS')),
    (gen_random_uuid(), 'Panama', 'PA', 'PAN',
        (SELECT id FROM currencies WHERE code = 'PAB')),
    (gen_random_uuid(), 'Papua New Guinea', 'PG', 'PNG',
        (SELECT id FROM currencies WHERE code = 'PGK')),
    (gen_random_uuid(), 'Paraguay', 'PY', 'PRY',
        (SELECT id FROM currencies WHERE code = 'PYG')),
    (gen_random_uuid(), 'Peru', 'PE', 'PER',
        (SELECT id FROM currencies WHERE code = 'PEN')),
    (gen_random_uuid(), 'Philippines', 'PH', 'PHL',
        (SELECT id FROM currencies WHERE code = 'PHP')),
    (gen_random_uuid(), 'Poland', 'PL', 'POL',
        (SELECT id FROM currencies WHERE code = 'PLN')),
    (gen_random_uuid(), 'Portugal', 'PT', 'PRT',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Qatar', 'QA', 'QAT',
        (SELECT id FROM currencies WHERE code = 'QAR')),
    (gen_random_uuid(), 'Romania', 'RO', 'ROU',
        (SELECT id FROM currencies WHERE code = 'RON')),
    (gen_random_uuid(), 'Russia', 'RU', 'RUS',
        (SELECT id FROM currencies WHERE code = 'RUB')),
    (gen_random_uuid(), 'Rwanda', 'RW', 'RWA',
        (SELECT id FROM currencies WHERE code = 'RWF')),
    (gen_random_uuid(), 'Saint Kitts and Nevis', 'KN', 'KNA',
        (SELECT id FROM currencies WHERE code = 'XCD')),
    (gen_random_uuid(), 'Saint Lucia', 'LC', 'LCA',
        (SELECT id FROM currencies WHERE code = 'XCD')),
    (gen_random_uuid(), 'Saint Vincent and the Grenadines', 'VC', 'VCT',
        (SELECT id FROM currencies WHERE code = 'XCD')),
    (gen_random_uuid(), 'Samoa', 'WS', 'WSM',
        (SELECT id FROM currencies WHERE code = 'WST')),
    (gen_random_uuid(), 'San Marino', 'SM', 'SMR',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Sao Tome and Principe', 'ST', 'STP',
        (SELECT id FROM currencies WHERE code = 'STN')),
    (gen_random_uuid(), 'Saudi Arabia', 'SA', 'SAU',
        (SELECT id FROM currencies WHERE code = 'SAR')),
    (gen_random_uuid(), 'Senegal', 'SN', 'SEN',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Serbia', 'RS', 'SRB',
        (SELECT id FROM currencies WHERE code = 'RSD')),
    (gen_random_uuid(), 'Seychelles', 'SC', 'SYC',
        (SELECT id FROM currencies WHERE code = 'SCR')),
    (gen_random_uuid(), 'Sierra Leone', 'SL', 'SLE',
        (SELECT id FROM currencies WHERE code = 'SLL')),
    (gen_random_uuid(), 'Singapore', 'SG', 'SGP',
        (SELECT id FROM currencies WHERE code = 'SGD')),
    (gen_random_uuid(), 'Slovakia', 'SK', 'SVK',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Slovenia', 'SI', 'SVN',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Solomon Islands', 'SB', 'SLB',
        (SELECT id FROM currencies WHERE code = 'SBD')),
    (gen_random_uuid(), 'Somalia', 'SO', 'SOM',
        (SELECT id FROM currencies WHERE code = 'SOS')),
    (gen_random_uuid(), 'South Africa', 'ZA', 'ZAF',
        (SELECT id FROM currencies WHERE code = 'ZAR')),
    (gen_random_uuid(), 'South Korea', 'KR', 'KOR',
        (SELECT id FROM currencies WHERE code = 'KRW')),
    (gen_random_uuid(), 'South Sudan', 'SS', 'SSD',
        (SELECT id FROM currencies WHERE code = 'SDG')),
    (gen_random_uuid(), 'Spain', 'ES', 'ESP',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Sri Lanka', 'LK', 'LKA',
        (SELECT id FROM currencies WHERE code = 'LKR')),
    (gen_random_uuid(), 'Sudan', 'SD', 'SDN',
        (SELECT id FROM currencies WHERE code = 'SDG')),
    (gen_random_uuid(), 'Suriname', 'SR', 'SUR',
        (SELECT id FROM currencies WHERE code = 'SRD')),
    (gen_random_uuid(), 'Sweden', 'SE', 'SWE',
        (SELECT id FROM currencies WHERE code = 'SEK')),
    (gen_random_uuid(), 'Switzerland', 'CH', 'CHE',
        (SELECT id FROM currencies WHERE code = 'CHF')),
    (gen_random_uuid(), 'Syria', 'SY', 'SYR',
        (SELECT id FROM currencies WHERE code = 'SYP')),
    (gen_random_uuid(), 'Taiwan', 'TW', 'TWN',
        (SELECT id FROM currencies WHERE code = 'TWD')),
    (gen_random_uuid(), 'Tajikistan', 'TJ', 'TJK',
        (SELECT id FROM currencies WHERE code = 'TJS')),
    (gen_random_uuid(), 'Tanzania', 'TZ', 'TZA',
        (SELECT id FROM currencies WHERE code = 'TZS')),
    (gen_random_uuid(), 'Thailand', 'TH', 'THA',
        (SELECT id FROM currencies WHERE code = 'THB')),
    (gen_random_uuid(), 'Timor-Leste', 'TL', 'TLS',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Togo', 'TG', 'TGO',
        (SELECT id FROM currencies WHERE code = 'XOF')),
    (gen_random_uuid(), 'Tonga', 'TO', 'TON',
        (SELECT id FROM currencies WHERE code = 'TOP')),
    (gen_random_uuid(), 'Trinidad and Tobago', 'TT', 'TTO',
        (SELECT id FROM currencies WHERE code = 'TTD')),
    (gen_random_uuid(), 'Tunisia', 'TN', 'TUN',
        (SELECT id FROM currencies WHERE code = 'TND')),
    (gen_random_uuid(), 'Turkey', 'TR', 'TUR',
        (SELECT id FROM currencies WHERE code = 'TRY')),
    (gen_random_uuid(), 'Turkmenistan', 'TM', 'TKM',
        (SELECT id FROM currencies WHERE code = 'TMT')),
    (gen_random_uuid(), 'Tuvalu', 'TV', 'TUV',
        (SELECT id FROM currencies WHERE code = 'AUD')),
    (gen_random_uuid(), 'Uganda', 'UG', 'UGA',
        (SELECT id FROM currencies WHERE code = 'UGX')),
    (gen_random_uuid(), 'Ukraine', 'UA', 'UKR',
        (SELECT id FROM currencies WHERE code = 'UAH')),
    (gen_random_uuid(), 'United Arab Emirates', 'AE', 'ARE',
        (SELECT id FROM currencies WHERE code = 'AED')),
    (gen_random_uuid(), 'United Kingdom', 'GB', 'GBR',
        (SELECT id FROM currencies WHERE code = 'GBP')),
    (gen_random_uuid(), 'United States', 'US', 'USA',
        (SELECT id FROM currencies WHERE code = 'USD')),
    (gen_random_uuid(), 'Uruguay', 'UY', 'URY',
        (SELECT id FROM currencies WHERE code = 'UYU')),
    (gen_random_uuid(), 'Uzbekistan', 'UZ', 'UZB',
        (SELECT id FROM currencies WHERE code = 'UZS')),
    (gen_random_uuid(), 'Vanuatu', 'VU', 'VUT',
        (SELECT id FROM currencies WHERE code = 'VUV')),
    (gen_random_uuid(), 'Vatican City', 'VA', 'VAT',
        (SELECT id FROM currencies WHERE code = 'EUR')),
    (gen_random_uuid(), 'Venezuela', 'VE', 'VEN',
        (SELECT id FROM currencies WHERE code = 'VES')),
    (gen_random_uuid(), 'Vietnam', 'VN', 'VNM',
        (SELECT id FROM currencies WHERE code = 'VND')),
    (gen_random_uuid(), 'Yemen', 'YE', 'YEM',
        (SELECT id FROM currencies WHERE code = 'YER')),
    (gen_random_uuid(), 'Zambia', 'ZM', 'ZMB',
        (SELECT id FROM currencies WHERE code = 'ZMW')),
    (gen_random_uuid(), 'Zimbabwe', 'ZW', 'ZWE',
        (SELECT id FROM currencies WHERE code = 'ZWL'));

-- -----------------------------------------------------------------
-- 4. country_phone_codes  (192 rows)
-- -----------------------------------------------------------------
INSERT INTO country_phone_codes (id, country_id, phone_code_id, is_primary) VALUES
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'US'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CA'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AG'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BB'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BS'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'DM'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'DO'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GD'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'JM'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KN'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LC'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TT'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'VC'),
        (SELECT id FROM phone_codes WHERE code = '+1'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'RU'),
        (SELECT id FROM phone_codes WHERE code = '+7'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KZ'),
        (SELECT id FROM phone_codes WHERE code = '+7'),
        false),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'EG'),
        (SELECT id FROM phone_codes WHERE code = '+20'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ZA'),
        (SELECT id FROM phone_codes WHERE code = '+27'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GR'),
        (SELECT id FROM phone_codes WHERE code = '+30'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NL'),
        (SELECT id FROM phone_codes WHERE code = '+31'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BE'),
        (SELECT id FROM phone_codes WHERE code = '+32'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'FR'),
        (SELECT id FROM phone_codes WHERE code = '+33'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ES'),
        (SELECT id FROM phone_codes WHERE code = '+34'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'HU'),
        (SELECT id FROM phone_codes WHERE code = '+36'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IT'),
        (SELECT id FROM phone_codes WHERE code = '+39'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'RO'),
        (SELECT id FROM phone_codes WHERE code = '+40'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CH'),
        (SELECT id FROM phone_codes WHERE code = '+41'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AT'),
        (SELECT id FROM phone_codes WHERE code = '+43'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GB'),
        (SELECT id FROM phone_codes WHERE code = '+44'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'DK'),
        (SELECT id FROM phone_codes WHERE code = '+45'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SE'),
        (SELECT id FROM phone_codes WHERE code = '+46'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NO'),
        (SELECT id FROM phone_codes WHERE code = '+47'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PL'),
        (SELECT id FROM phone_codes WHERE code = '+48'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'DE'),
        (SELECT id FROM phone_codes WHERE code = '+49'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PE'),
        (SELECT id FROM phone_codes WHERE code = '+51'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MX'),
        (SELECT id FROM phone_codes WHERE code = '+52'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CU'),
        (SELECT id FROM phone_codes WHERE code = '+53'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AR'),
        (SELECT id FROM phone_codes WHERE code = '+54'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BR'),
        (SELECT id FROM phone_codes WHERE code = '+55'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CL'),
        (SELECT id FROM phone_codes WHERE code = '+56'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CO'),
        (SELECT id FROM phone_codes WHERE code = '+57'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'VE'),
        (SELECT id FROM phone_codes WHERE code = '+58'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MY'),
        (SELECT id FROM phone_codes WHERE code = '+60'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AU'),
        (SELECT id FROM phone_codes WHERE code = '+61'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ID'),
        (SELECT id FROM phone_codes WHERE code = '+62'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PH'),
        (SELECT id FROM phone_codes WHERE code = '+63'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NZ'),
        (SELECT id FROM phone_codes WHERE code = '+64'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SG'),
        (SELECT id FROM phone_codes WHERE code = '+65'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TH'),
        (SELECT id FROM phone_codes WHERE code = '+66'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'JP'),
        (SELECT id FROM phone_codes WHERE code = '+81'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KR'),
        (SELECT id FROM phone_codes WHERE code = '+82'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'VN'),
        (SELECT id FROM phone_codes WHERE code = '+84'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CN'),
        (SELECT id FROM phone_codes WHERE code = '+86'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TR'),
        (SELECT id FROM phone_codes WHERE code = '+90'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IN'),
        (SELECT id FROM phone_codes WHERE code = '+91'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PK'),
        (SELECT id FROM phone_codes WHERE code = '+92'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AF'),
        (SELECT id FROM phone_codes WHERE code = '+93'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LK'),
        (SELECT id FROM phone_codes WHERE code = '+94'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MM'),
        (SELECT id FROM phone_codes WHERE code = '+95'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IR'),
        (SELECT id FROM phone_codes WHERE code = '+98'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MA'),
        (SELECT id FROM phone_codes WHERE code = '+212'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'DZ'),
        (SELECT id FROM phone_codes WHERE code = '+213'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TN'),
        (SELECT id FROM phone_codes WHERE code = '+216'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LY'),
        (SELECT id FROM phone_codes WHERE code = '+218'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GM'),
        (SELECT id FROM phone_codes WHERE code = '+220'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SN'),
        (SELECT id FROM phone_codes WHERE code = '+221'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MR'),
        (SELECT id FROM phone_codes WHERE code = '+222'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ML'),
        (SELECT id FROM phone_codes WHERE code = '+223'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GN'),
        (SELECT id FROM phone_codes WHERE code = '+224'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BF'),
        (SELECT id FROM phone_codes WHERE code = '+226'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NE'),
        (SELECT id FROM phone_codes WHERE code = '+227'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TG'),
        (SELECT id FROM phone_codes WHERE code = '+228'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BJ'),
        (SELECT id FROM phone_codes WHERE code = '+229'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MU'),
        (SELECT id FROM phone_codes WHERE code = '+230'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LR'),
        (SELECT id FROM phone_codes WHERE code = '+231'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SL'),
        (SELECT id FROM phone_codes WHERE code = '+232'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GH'),
        (SELECT id FROM phone_codes WHERE code = '+233'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NG'),
        (SELECT id FROM phone_codes WHERE code = '+234'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TD'),
        (SELECT id FROM phone_codes WHERE code = '+235'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CF'),
        (SELECT id FROM phone_codes WHERE code = '+236'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CM'),
        (SELECT id FROM phone_codes WHERE code = '+237'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CV'),
        (SELECT id FROM phone_codes WHERE code = '+238'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ST'),
        (SELECT id FROM phone_codes WHERE code = '+239'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GQ'),
        (SELECT id FROM phone_codes WHERE code = '+240'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GA'),
        (SELECT id FROM phone_codes WHERE code = '+241'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CG'),
        (SELECT id FROM phone_codes WHERE code = '+242'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CD'),
        (SELECT id FROM phone_codes WHERE code = '+243'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AO'),
        (SELECT id FROM phone_codes WHERE code = '+244'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GW'),
        (SELECT id FROM phone_codes WHERE code = '+245'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SC'),
        (SELECT id FROM phone_codes WHERE code = '+248'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SD'),
        (SELECT id FROM phone_codes WHERE code = '+249'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'RW'),
        (SELECT id FROM phone_codes WHERE code = '+250'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ET'),
        (SELECT id FROM phone_codes WHERE code = '+251'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SO'),
        (SELECT id FROM phone_codes WHERE code = '+252'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'DJ'),
        (SELECT id FROM phone_codes WHERE code = '+253'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KE'),
        (SELECT id FROM phone_codes WHERE code = '+254'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TZ'),
        (SELECT id FROM phone_codes WHERE code = '+255'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'UG'),
        (SELECT id FROM phone_codes WHERE code = '+256'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BI'),
        (SELECT id FROM phone_codes WHERE code = '+257'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MZ'),
        (SELECT id FROM phone_codes WHERE code = '+258'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ZM'),
        (SELECT id FROM phone_codes WHERE code = '+260'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MG'),
        (SELECT id FROM phone_codes WHERE code = '+261'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ZW'),
        (SELECT id FROM phone_codes WHERE code = '+263'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NA'),
        (SELECT id FROM phone_codes WHERE code = '+264'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MW'),
        (SELECT id FROM phone_codes WHERE code = '+265'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LS'),
        (SELECT id FROM phone_codes WHERE code = '+266'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BW'),
        (SELECT id FROM phone_codes WHERE code = '+267'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SZ'),
        (SELECT id FROM phone_codes WHERE code = '+268'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KM'),
        (SELECT id FROM phone_codes WHERE code = '+269'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ER'),
        (SELECT id FROM phone_codes WHERE code = '+291'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PT'),
        (SELECT id FROM phone_codes WHERE code = '+351'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LU'),
        (SELECT id FROM phone_codes WHERE code = '+352'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IE'),
        (SELECT id FROM phone_codes WHERE code = '+353'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IS'),
        (SELECT id FROM phone_codes WHERE code = '+354'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AL'),
        (SELECT id FROM phone_codes WHERE code = '+355'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MT'),
        (SELECT id FROM phone_codes WHERE code = '+356'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CY'),
        (SELECT id FROM phone_codes WHERE code = '+357'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'FI'),
        (SELECT id FROM phone_codes WHERE code = '+358'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BG'),
        (SELECT id FROM phone_codes WHERE code = '+359'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LT'),
        (SELECT id FROM phone_codes WHERE code = '+370'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LV'),
        (SELECT id FROM phone_codes WHERE code = '+371'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'EE'),
        (SELECT id FROM phone_codes WHERE code = '+372'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MD'),
        (SELECT id FROM phone_codes WHERE code = '+373'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AM'),
        (SELECT id FROM phone_codes WHERE code = '+374'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BY'),
        (SELECT id FROM phone_codes WHERE code = '+375'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AD'),
        (SELECT id FROM phone_codes WHERE code = '+376'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MC'),
        (SELECT id FROM phone_codes WHERE code = '+377'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'UA'),
        (SELECT id FROM phone_codes WHERE code = '+380'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'RS'),
        (SELECT id FROM phone_codes WHERE code = '+381'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'ME'),
        (SELECT id FROM phone_codes WHERE code = '+382'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'HR'),
        (SELECT id FROM phone_codes WHERE code = '+385'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SI'),
        (SELECT id FROM phone_codes WHERE code = '+386'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BA'),
        (SELECT id FROM phone_codes WHERE code = '+387'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MK'),
        (SELECT id FROM phone_codes WHERE code = '+389'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CZ'),
        (SELECT id FROM phone_codes WHERE code = '+420'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SK'),
        (SELECT id FROM phone_codes WHERE code = '+421'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LI'),
        (SELECT id FROM phone_codes WHERE code = '+423'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BZ'),
        (SELECT id FROM phone_codes WHERE code = '+501'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GT'),
        (SELECT id FROM phone_codes WHERE code = '+502'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SV'),
        (SELECT id FROM phone_codes WHERE code = '+503'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'HN'),
        (SELECT id FROM phone_codes WHERE code = '+504'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NI'),
        (SELECT id FROM phone_codes WHERE code = '+505'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'CR'),
        (SELECT id FROM phone_codes WHERE code = '+506'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PA'),
        (SELECT id FROM phone_codes WHERE code = '+507'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'HT'),
        (SELECT id FROM phone_codes WHERE code = '+509'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BO'),
        (SELECT id FROM phone_codes WHERE code = '+591'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GY'),
        (SELECT id FROM phone_codes WHERE code = '+592'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'EC'),
        (SELECT id FROM phone_codes WHERE code = '+593'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PY'),
        (SELECT id FROM phone_codes WHERE code = '+595'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SR'),
        (SELECT id FROM phone_codes WHERE code = '+597'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'UY'),
        (SELECT id FROM phone_codes WHERE code = '+598'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TL'),
        (SELECT id FROM phone_codes WHERE code = '+670'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BN'),
        (SELECT id FROM phone_codes WHERE code = '+673'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NR'),
        (SELECT id FROM phone_codes WHERE code = '+674'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PG'),
        (SELECT id FROM phone_codes WHERE code = '+675'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TO'),
        (SELECT id FROM phone_codes WHERE code = '+676'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SB'),
        (SELECT id FROM phone_codes WHERE code = '+677'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'VU'),
        (SELECT id FROM phone_codes WHERE code = '+678'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'FJ'),
        (SELECT id FROM phone_codes WHERE code = '+679'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PW'),
        (SELECT id FROM phone_codes WHERE code = '+680'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'WS'),
        (SELECT id FROM phone_codes WHERE code = '+685'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KI'),
        (SELECT id FROM phone_codes WHERE code = '+686'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TV'),
        (SELECT id FROM phone_codes WHERE code = '+688'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'FM'),
        (SELECT id FROM phone_codes WHERE code = '+691'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MH'),
        (SELECT id FROM phone_codes WHERE code = '+692'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KP'),
        (SELECT id FROM phone_codes WHERE code = '+850'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KH'),
        (SELECT id FROM phone_codes WHERE code = '+855'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LA'),
        (SELECT id FROM phone_codes WHERE code = '+856'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BD'),
        (SELECT id FROM phone_codes WHERE code = '+880'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TW'),
        (SELECT id FROM phone_codes WHERE code = '+886'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MV'),
        (SELECT id FROM phone_codes WHERE code = '+960'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'LB'),
        (SELECT id FROM phone_codes WHERE code = '+961'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'JO'),
        (SELECT id FROM phone_codes WHERE code = '+962'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SY'),
        (SELECT id FROM phone_codes WHERE code = '+963'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IQ'),
        (SELECT id FROM phone_codes WHERE code = '+964'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KW'),
        (SELECT id FROM phone_codes WHERE code = '+965'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'SA'),
        (SELECT id FROM phone_codes WHERE code = '+966'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'YE'),
        (SELECT id FROM phone_codes WHERE code = '+967'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'OM'),
        (SELECT id FROM phone_codes WHERE code = '+968'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'PS'),
        (SELECT id FROM phone_codes WHERE code = '+970'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AE'),
        (SELECT id FROM phone_codes WHERE code = '+971'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'IL'),
        (SELECT id FROM phone_codes WHERE code = '+972'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BH'),
        (SELECT id FROM phone_codes WHERE code = '+973'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'QA'),
        (SELECT id FROM phone_codes WHERE code = '+974'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'BT'),
        (SELECT id FROM phone_codes WHERE code = '+975'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'MN'),
        (SELECT id FROM phone_codes WHERE code = '+976'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'NP'),
        (SELECT id FROM phone_codes WHERE code = '+977'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TJ'),
        (SELECT id FROM phone_codes WHERE code = '+992'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'TM'),
        (SELECT id FROM phone_codes WHERE code = '+993'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'AZ'),
        (SELECT id FROM phone_codes WHERE code = '+994'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'GE'),
        (SELECT id FROM phone_codes WHERE code = '+995'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'KG'),
        (SELECT id FROM phone_codes WHERE code = '+996'),
        true),
    (gen_random_uuid(),
        (SELECT id FROM countries WHERE iso_code_2 = 'UZ'),
        (SELECT id FROM phone_codes WHERE code = '+998'),
        true);

COMMIT;